### ISSUE TITLE
The clj-i18n .jar is distributed as an AOT-compiled lib

### ISSUE THREAD

**Issue by vemv** [puppetlabs/clj-i18n#47]
Hi!

The distributed clj-i18n artifact is AOT-compiled:

![image](https://user-images.githubusercontent.com/1162994/107844356-ec4d9800-6dd2-11eb-86b7-6e232e7be97f.png)

This is known as a source of issues ([ref](https://github.com/camsaul/methodical/issues/40#issuecomment-775446224)) and would appreciate if newer releases were source-only.

Thanks - V

**Comment by vemv** [comment]
Hi @jonathannewman, sorry to bother. What do you think of this issue?

I verified locally that this project's `lein test` is able to succeed without :aot.

A specific problem of AOT is that it couples bytecode to a specific Clojure compiler. e.g. there's no particular guarantee that .class bytecode emitted by Clojure 1._x_ will be able to be consumed by Clojure 1._y_

**Comment by jonathannewman** [comment]
Thanks @vemv I think it makes sense to remove the AOT compilation.  If you put up a PR against the repo, I'd be happy to review it.

**Comment by vemv** [comment]
Hi again, thanks for the response!

The only necessary changes are removing :aot and :main from project.clj. Out of that, `make` followed by `lein test` will pass.

I'd rather not open a PR because of its trivial size, are you ok with that?

**Comment by jonathannewman** [comment]
I'd prefer a PR for several reasons:  

- It gives an opportunity for other contributors to weigh in on the merit of the work and to make suggestions that we may not be aware of
- It helps assure that we have a good history of the changes made and why they are made
- It makes it easier to revert the work if issues arise

I realize that the change may seem trivial from an implementation standpoint, but it is in use as part of Puppet's Enterprise product and thus has a required level of rigor.

I appreciate your understanding, and thanks again for bringing it up.

**Comment by vemv** [comment]
Thanks! I agree.

To prevent any IP concerns from getting in the way, could you open the PR? You can cc/ me in the PR itself and would be happy to provide any missing info, rationale, etc.

**Comment by jonathannewman** [comment]
@vemv see https://github.com/puppetlabs/clj-i18n/pull/48

**Comment by vemv** [comment]
Thanks! I subscribed to its notifications.

**Comment by jonathannewman** [comment]
0.9.1 should be on clojars now with the change.  Thanks for the submission @vemv  !  Going to close this since we have resolved the issue.
